-- MySQL Script generated by MySQL Workbench
-- Mon Aug  5 20:05:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vanguard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vanguard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vanguard` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Vanguard` ;

-- -----------------------------------------------------
-- Table `Vanguard`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`estado` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`cidades` (
  `cidade_id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(100) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`, `estado_id`),
  INDEX `fk_Cidades_Estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_Cidades_Estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `Vanguard`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_estado_id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `cidades_id` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `avaliacao` INT(6) NULL,
  `comentario` TEXT NULL,
  `cpf` CHAR(11) NOT NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`id`, `cidades_id`, `estado_estado_id`),
  INDEX `fk_Usuario_Cidades1_idx` (`cidades_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_usuario_estado1_idx` (`estado_estado_id` ASC),
  CONSTRAINT `fk_Usuario_Cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `Vanguard`.`cidades` (`cidade_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_estado1`
    FOREIGN KEY (`estado_estado_id`)
    REFERENCES `Vanguard`.`estado` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`produto` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `classe` VARCHAR(20) NOT NULL,
  `descricao` TEXT NOT NULL,
  `imagem` LONGBLOB NOT NULL,
  PRIMARY KEY (`produto_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_carrinho_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_carrinho_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`produto_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`produto_carrinho` (
  `produto_carrinho_id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `carrinho_id` INT NOT NULL,
  PRIMARY KEY (`produto_carrinho_id`, `produto_id`, `carrinho_id`),
  INDEX `fk_Produto_carrinho_Produto1_idx` (`produto_id` ASC),
  INDEX `fk_Produto_carrinho_carrinho1_idx` (`carrinho_id` ASC),
  CONSTRAINT `fk_Produto_carrinho_Produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `Vanguard`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_carrinho_carrinho1`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `Vanguard`.`carrinho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`funcionario` (
  `nome` VARCHAR(255) NOT NULL,
  `usuario_id` INT NOT NULL,
  `usuario_cidades_id` INT NOT NULL,
  `usuario_cidades_estado_id` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario_id`, `usuario_cidades_id`, `usuario_cidades_estado_id`),
  CONSTRAINT `fk_funcionario_Usuario1`
    FOREIGN KEY (`usuario_id` , `usuario_cidades_id`)
    REFERENCES `Vanguard`.`usuario` (`id` , `cidades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`relatorio` (
  `relatorio_id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `funcionario_usuario_id` INT NOT NULL,
  `funcionario_usuario_cidades_id` INT NULL,
  `funcionario_usuario_cidades_estado_id` INT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`relatorio_id`, `funcionario_usuario_id`, `funcionario_usuario_cidades_id`, `funcionario_usuario_cidades_estado_id`),
  INDEX `fk_relatorio_funcionario1_idx` (`funcionario_usuario_id` ASC, `funcionario_usuario_cidades_id` ASC, `funcionario_usuario_cidades_estado_id` ASC),
  CONSTRAINT `fk_relatorio_funcionario1`
    FOREIGN KEY (`funcionario_usuario_id` , `funcionario_usuario_cidades_id` , `funcionario_usuario_cidades_estado_id`)
    REFERENCES `Vanguard`.`funcionario` (`usuario_id` , `usuario_cidades_id` , `usuario_cidades_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vanguard`.`solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vanguard`.`solicitacao` (
  `titulo` VARCHAR(50) NOT NULL,
  `comentario` TEXT NOT NULL,
  `solicitacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`solicitacao_id`, `usuario_id`),
  INDEX `fk_solicitacao_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_solicitacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Vanguard`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
